---
title: "global_warming_regressor"
author: "Rowan Lavelle"
date: "12/5/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
```

```{r}
data = read.csv('data/GlobalTemperatures.csv', header=T)
data = data[-(1:2640),]
plot(data$LandAverageTemperature, type='l')
```


```{r}
regressor = function(X,y){
  n = dim(X)[1]
  m = dim(X)[2]
  
  g = n
  v0 = 2
  sigma20 = 1
  
  N = 1000
  Hg = (g/(g+1) * X %*% solve(t(X)%*%X) %*% t(X))
  SSRg = t(y) %*% (diag(1,nrow=n) - Hg) %*% y
  sigma2 = 1/rgamma(N, (v0+n)/2, (v0*sigma20+SSRg)/2)
  
  Vb = (g/(g+1)) * solve(t(X)%*%X)
  Eb = Vb %*% t(X) %*% y
  
  E = matrix(rnorm(N*m,0,sqrt(sigma2)),N,m)
  beta = t(t(E %*% chol(Vb)) + c(Eb))
  
  beta.post.intervals = apply(beta, MARGIN=2, FUN=quantile, probs=c(0.025, 0.5, 0.975))
  BETAols = solve(t(X) %*% X) %*% t(X) %*% y
  
  return(beta)
}
```

```{r}
adj.r2 = function(y,y.pred,p){
  r2 = 1-(sum((y-y.pred)^2)/sum((y-mean(y))^2))
  
  N = length(y)
  adjr2 = 1 - ((1-r2)*(N-1))/(N-p-1)
  return(adjr2)
}
```

```{r}
# just linear term
y = data$LandAverageTemperature
size = length(y)
x = seq(1,size)
X = cbind(rep(1, size), x)

beta = regressor(X,y)
beta.bayes = as.matrix(colMeans(beta))
y.pred.bayes.simple = X %*% beta.bayes
beta.post.intervals = apply(beta, MARGIN=2, FUN=quantile, probs=c(0.025, 0.5, 0.975))
beta.post.intervals

bayes.error.simple = (1/size)*sum((y-y.pred.bayes.simple)^2)
bayes.error.simple

adj.r2(y,y.pred.bayes.simple,2)

# harmonic regression
y = data$LandAverageTemperature
size = length(y)
x = seq(1,size)
X = cbind(rep(1, size), sin(2*pi*x/12), cos(2*pi*x/12))

beta = regressor(X,y)
beta.bayes = as.matrix(colMeans(beta))
y.pred.bayes.sin.cos = X %*% beta.bayes
beta.post.intervals = apply(beta, MARGIN=2, FUN=quantile, probs=c(0.025, 0.5, 0.975))
beta.post.intervals

bayes.error.sin.cos = (1/size)*sum((y-y.pred.bayes.sin.cos)^2)
bayes.error.sin.cos

adj.r2(y,y.pred.bayes.sin.cos,3)

# harmonic + linear regression
y = data$LandAverageTemperature
size = length(y)
x = seq(1,size)
X = cbind(rep(1, size), x, sin(2*pi*x/12), cos(2*pi*x/12))

beta = regressor(X,y)
beta.bayes = as.matrix(colMeans(beta))
y.pred.bayes.lin.sin.cos = X %*% beta.bayes
beta.post.intervals = apply(beta, MARGIN=2, FUN=quantile, probs=c(0.025, 0.5, 0.975))
beta.post.intervals

bayes.error.lin.sin.cos = (1/size)*sum((y-y.pred.bayes.lin.sin.cos)^2)
bayes.error.lin.sin.cos
adj.r2(y,y.pred.bayes.lin.sin.cos,4)

# harmonic + linear + poly regression
y = data$LandAverageTemperature
size = length(y)
x = seq(1,size)
X = cbind(rep(1, size), x, x^2, sin(2*pi*x/12), cos(2*pi*x/12))

beta = regressor(X,y)
beta.bayes = as.matrix(colMeans(beta))
y.pred.bayes.lin.sin.cos.poly = X %*% beta.bayes
beta.post.intervals = apply(beta, MARGIN=2, FUN=quantile, probs=c(0.025, 0.5, 0.975))
beta.post.intervals

bayes.error.lin.sin.cos.poly = (1/size)*sum((y-y.pred.bayes.lin.sin.cos.poly)^2)
bayes.error.lin.sin.cos.poly
adj.r2(y,y.pred.bayes.lin.sin.cos.poly,5)

```


```{r}
plot(y, type='l')
lines(y.pred.bayes.simple, col='green')
lines(y.pred.bayes.sin.cos, col='red')

plot(y, type='l')
lines(y.pred.bayes.simple, col='green')
lines(y.pred.bayes.lin.sin.cos, col='purple')
```

```{r}
resid.har = y-y.pred.bayes.sin.cos
resid.lin.har = y-y.pred.bayes.lin.sin.cos
X.har = cbind(rep(1,length(resid.har)), seq(1,length(resid.har)))
X.lin.har = cbind(rep(1,length(resid.lin.har)), seq(1,length(resid.lin.har)))
beta.har = solve(t(X.har)%*%X.har)%*%t(X.har)%*%resid.har
beta.lin.har = solve(t(X.lin.har)%*%X.lin.har)%*%t(X.lin.har)%*%resid.lin.har
y.har = X.har %*% beta.har
y.lin.har = X.lin.har %*% beta.lin.har
plot(resid.har, col=adjustcolor( "red", alpha.f = 0.5))
lines(resid.lin.har, col=adjustcolor( "black", alpha.f = 0.5), type='p')
lines(y.har, col='red')
lines(y.lin.har, col='black')
```
```{r}
# legend("topleft", inset = 0.01, legend=c("Actual", "Predicted"),col=c("green", "blue"), lty = 1:2)
```

```{r}
# harmonic + linear regression
y = data$LandAverageTemperature
size = length(y)
x = seq(1,size)
c

beta = regressor(X,y)
beta.bayes = as.matrix(colMeans(beta))
y.pred.bayes.lin.sin.cos = X %*% beta.bayes
beta.post.intervals = apply(beta, MARGIN=2, FUN=quantile, probs=c(0.025, 0.5, 0.975))
beta.post.intervals

bayes.error.lin.sin.cos = (1/size)*sum((y-y.pred.bayes.lin.sin.cos)^2)
bayes.error.lin.sin.cos
```

```{r}
apply(beta, MARGIN=2, FUN=function(col){
  h = hist(col,prob=TRUE)
  d = density(col)
  lines(d, col='black')
})
```

```{r}
y = data$LandAverageTemperature
x.future = seq(size,size+120)
X = cbind(rep(1, length(x.future)), x.future, sin(2*pi*x.future/12), cos(2*pi*x.future/12))
y.pred = X %*% beta.bayes
plot(seq(1,size),y, type='l',
     xlim=c(0,size+120),
     ylim=c(0,max(y.pred)))

lines(c(size,x.future),c(y[length(y)],y.pred), col='red')
```










